// @ts-check

/**
  @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
    {
      type: 'html',
      value: '<hr style="margin: 0.3rem 0;" />',
      defaultStyle: true,
    },
    'static/openapi',
    'static/client-libraries',
  ],
};

export default sidebars;
