name: Documentation

on:
  push:
    paths:
      - 'docs/**'

jobs:

  deploy-docs:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        working-directory: .
        run: npm install

      - name: Build documentation
        working-directory: .
        env:
          SITE_URL: https://pbinitiative.github.io
          BASE_URL: /zenbpm-docusaurus
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
